services:
  mysql5.7:
    image: swaycn/mysql:5.7.44
    container_name: mysql5.7
    ports:
      - "33062:3306"
    volumes:
      - /download/dapp/mysql5.7/mysql:/etc/mysql
      - /download/dapp/mysql5.7/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    restart: always
  phpmyadmin:
    restart: always
    image: swaycn/phpmyadmin:5.2.3-fpm-alpine
    ports:
      - 7000:80
    environment:
      - PMA_HOSTS=mysql5.7
  redis8:
    image: swaycn/redis:8.2.1-alpine3.22
    container_name: redis8
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always
networks:
  default:
    external: true
    name: web